apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: spawners.dossier.unito.it
spec:
  group: dossier.unito.it
  names:
    plural: spawners
    singular: spawner
    kind: Spawner
    listKind: SpawnerList
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Dossier Spawner to remote locations
          type: object
          properties:
            apiVersion:
              description: >-
                APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the
                latest internal value, and may reject unrecognized values. More
                info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: >-
                Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the
                client submits requests to. Cannot be updated. In CamelCase.
                More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: SpawnerSpec defines the state of a Spawner
              type: object
              required:
                - class
              properties:
                attributes:
                  description: >-
                    Spawner attribbutes configured by the system administrator. Attributes can be different
                    for each spawner class.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                class:
                  description: >-
                    A fully qualified class name of a Jupyter Notebooks spawner. The class must extend the
                    jupyterhub.spawner.Spawner class.
                    More info:
                    https://github.com/jupyterhub/jupyterhub/blob/main/docs/source/reference/spawners.md
                  type: string
                options:
                  description: >-
                    Configurable options of the selected spawner class that must be populated by each user.
                    Options can be different for each spawner class
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                tenants:
                  description: The set of Tenants enabled to use this Spawner
                  type: array
                  items:
                    type: string
